### ISSUE TITLE
The generated OG images are not copied to the final build directory

### ISSUE THREAD

**Issue by tometo-dev** [kettanaito/remix-og-image#15]
When the `build` command is run, it generates the og images and puts them in the path specified (e.g. `public/og`), but the images are not present in the final build directory. Ideally, they should also be present (and updated) under the build folder after the build finishes.

I suppose this happens because the plugin build happens **after** remix has already finished building (please refer to the attached screenshot)
![image](https://github.com/user-attachments/assets/3ec4ec42-ae4a-4834-8ddc-5f34da142260)

**Comment by tometo-dev** [comment]
@kettanaito afaik, once the build is generated, the server no longer references the `/public` folder and all relative routes resolve to the built output. that's also the behavior when i used the `npm run start` in a remix project.

i may be wrong here. let me check and come back.

**Comment by kettanaito** [comment]
No, I think you are totally right. The `public` dir may be something the preview server uses and that's it. A great catch here! 

Since the plugin is not meant for development, only for builds, I think we should resolve the `outputDirectory` relative to the assets output directory. We can grab the user's Remix config at any time and get the directory from there:

https://github.com/kettanaito/remix-og-image/blob/5a0e309b27f742c7cb7cfaf05c0ae24d4343fa2e/src/plugin.ts#L86

@tometo-dev, please, would you like to open a pull request for this?

**Comment by kettanaito** [comment]
So, per [Remix docs](https://remix.run/docs/en/main/file-conventions/remix-config#assetsbuilddirectory), `assetsBuildDirectory` is `public/build` by default. This means that the public directory is always a part of the deployment.

**Comment by tometo-dev** [comment]
@kettanaito the `assetsBuildDirectory` seems to be available when using `remix config` (i.e. remix compiler) and is apparently not present when using `vite config`. When using vite, the [buildDirectory](https://remix.run/docs/en/main/file-conventions/vite-config#builddirectory) gives the path to the `"build"` folder, which defaults to `/build`.

**Comment by kettanaito** [comment]
## Released: v0.3.1 🎉

This has been released in v0.3.1!

- 📄 [**Release notes**](https://github.com/kettanaito/remix-og-image/releases/tag/v0.3.1)
- 📦 [npm package](https://www.npmjs.com/package/remix-og-image/v/0.3.1)

Make sure to always update to the latest version (`npm i remix-og-image@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by kettanaito** [comment]
Just verified that this works as expected with the default Remix config on Cloudflare 🎉 Thank you for helping with this, @tometo-dev!
