### ISSUE TITLE
Consider disabling the plugin during `serve` builds

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/remix-og-image#9]
It's nice to monitor the image you get during the time you work on the image, but it's unnecessary usage of power, imo. The plugin guarantees WYSIWYG at this point, and you are much better off checking your work by viewing the designated OG image route you already have. 

I think the plugin should do nothing during `serve` (i.e. dev build). You can run the build to make it generate images to check them.

**Comment by kettanaito** [comment]
## Released: v0.3.0 🎉

This has been released in v0.3.0!

- 📄 [**Release notes**](https://github.com/kettanaito/remix-og-image/releases/tag/v0.3.0)
- 📦 [npm package](https://www.npmjs.com/package/remix-og-image/v/0.3.0)

Make sure to always update to the latest version (`npm i remix-og-image@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by tometo-dev** [comment]
yeah makes sense. also really like how you document the commits. i followed through the commits, wondered the reason why and here it was, all documented. 😊

**Comment by kettanaito** [comment]
@tometo-dev, running during dev is simply not worth it. Glad you found more reasoning behind that decision!
